component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/data/.*
- ./bin/data/baseline/.*
- ./bin/data/hibernate/.*
- ./bin/de/.*
- ./bin/de/nava/.*
- ./bin/de/nava/informa/.*
- ./bin/de/nava/informa/core/.*
- ./bin/de/nava/informa/exporters/.*
- ./bin/de/nava/informa/impl/.*
- ./bin/de/nava/informa/impl/basic/.*
- ./bin/de/nava/informa/impl/hibernate/.*
- ./bin/de/nava/informa/parsers/.*
- ./bin/de/nava/informa/search/.*
- ./bin/de/nava/informa/test/.*
- ./bin/de/nava/informa/utils/.*
- ./bin/de/nava/informa/utils/cleaner/.*
- ./bin/de/nava/informa/utils/manager/.*
- ./bin/de/nava/informa/utils/manager/hibernate/.*
- ./bin/de/nava/informa/utils/manager/memory/.*
- ./bin/de/nava/informa/utils/poller/.*
- ./bin/de/nava/informa/utils/toolkit/.*
- ./bin/export/.*
- ./bin/import/.*
- ./bin/jdo/.*
- ./bin/misc/.*
- ./bin/search/.*
- ./config/.*
- ./docs/.*
- ./docs/apidocs/.*
- ./docs/apidocs/de/.*
- ./docs/apidocs/de/nava/.*
- ./docs/apidocs/de/nava/informa/.*
- ./docs/apidocs/de/nava/informa/core/.*
- ./docs/apidocs/de/nava/informa/core/class-use/.*
- ./docs/apidocs/de/nava/informa/exporters/.*
- ./docs/apidocs/de/nava/informa/exporters/class-use/.*
- ./docs/apidocs/de/nava/informa/impl/.*
- ./docs/apidocs/de/nava/informa/impl/basic/.*
- ./docs/apidocs/de/nava/informa/impl/basic/class-use/.*
- ./docs/apidocs/de/nava/informa/impl/hibernate/.*
- ./docs/apidocs/de/nava/informa/impl/hibernate/class-use/.*
- ./docs/apidocs/de/nava/informa/parsers/.*
- ./docs/apidocs/de/nava/informa/parsers/class-use/.*
- ./docs/apidocs/de/nava/informa/search/.*
- ./docs/apidocs/de/nava/informa/search/class-use/.*
- ./docs/apidocs/de/nava/informa/utils/.*
- ./docs/apidocs/de/nava/informa/utils/class-use/.*
- ./docs/apidocs/de/nava/informa/utils/cleaner/.*
- ./docs/apidocs/de/nava/informa/utils/cleaner/class-use/.*
- ./docs/apidocs/de/nava/informa/utils/manager/.*
- ./docs/apidocs/de/nava/informa/utils/manager/class-use/.*
- ./docs/apidocs/de/nava/informa/utils/manager/hibernate/.*
- ./docs/apidocs/de/nava/informa/utils/manager/hibernate/class-use/.*
- ./docs/apidocs/de/nava/informa/utils/manager/memory/.*
- ./docs/apidocs/de/nava/informa/utils/manager/memory/class-use/.*
- ./docs/apidocs/de/nava/informa/utils/poller/.*
- ./docs/apidocs/de/nava/informa/utils/poller/class-use/.*
- ./docs/apidocs/de/nava/informa/utils/toolkit/.*
- ./docs/apidocs/de/nava/informa/utils/toolkit/class-use/.*
- ./docs/develop/.*
- ./lib/.*
- ./sql/.*
- ./sql/schema/.*
- ./sql/schema/hsqldb/.*
- ./sql/schema/mysql/.*
- ./sql/schema/postgres/.*
- ./test/.*
- ./test/data/.*
- ./test/data/baseline/.*
- ./test/data/hibernate/.*
- ./test/export/.*
- ./test/import/.*
- ./test/jdo/.*
- ./test/misc/.*
- ./test/search/.*
- ./xdocs/.*
- ./xdocs/images/.*
